#!/bin/bash

# import the workspace into JupyterLab
jupyter lab workspaces import ${REPO_DIR}/binder/workspace.json

# run daemons
yaqd-fake-continuous-hardware --config ${REPO_DIR}/binder/yaqd-fake-continuous-hardware-config.toml &>/dev/null &
disown
